apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

images:
- name: quay.io/wpernath/quarkus-grumpycat:v0.2.1
  newName: quay.io/wpernath/quarkus-grumpycat
  newTag: v0.2.2